var _config = {
			name:"database_connection_config",
			fields:[
					{
					showName:"",
					name:"service_type",
					must_send:false,
					must_save:true,
					type:"hidden",
					placeholder:"",
					value:"service_database_connection_config"
					},
  				{
  					showName:"",
  					name:"type",
  					must_send:false,
  					must_save:true,
  					type:"hidden",
  					placeholder:"",
  					value:"database_connection_config"
  				},
  				{
  					showName:"service",
  					name:"service",
  					must_send:true,
  					must_save:true,
  					type:"input",
  					placeholder:"服务访问名称",
  				},
  				{
  					showName:"备注",
  					name:"backup",
  					must_send:false,
  					must_save:false,
  					type:"input",
  					placeholder:"",
  				},
  				{
  					showName:"是否需要登陆，login_require",
  					name:"login_require",
  					must_send:false,
  					must_save:true,
  					type:"input",
  					placeholder:"是否需要登陆",
  					value:"true"
  				},

  				{
  					showName:"database_type ,数据库类型",
  					name:"database_type",
  					must_send:false,
  					must_save:true,
  					type:"input",
  					placeholder:"mysql,oracle,sqlserver",
  					value:"mysql"
  				},
  				{
  					showName:"class_name，驱动,com.mysql.jdbc.Driver,org.sqlite.JDBC",
  					name:"class_name",
  					must_send:false,
  					must_save:true,
  					type:"input",
  					placeholder:"驱动",
  					value:"com.mysql.jdbc.Driver"
  				},
  				{
  					showName:"host,数据库ip",
  					name:"host",
  					must_send:false,
  					must_save:false,
  					type:"input",
  					placeholder:"数据库ip",
  					value:""
  				},
  			
  				
  				{
  					showName:"username ,用户名",
  					name:"username",
  					must_send:false,
  					must_save:false,
  					type:"input",
  					placeholder:"用户名",
  					value:""
  				},

  				{
  					showName:'password,密码',
  					name:"password",
  					must_send:false,
  					must_save:false,
  					type:"input",
  					placeholder:"密码",
  					value:""
  				},
  				{
  					showName:'database,数据库',
  					name:"database",
  					must_send:false,
  					must_save:false,
  					type:"input",
  					placeholder:"数据库",
  					value:""
  				},
  				{
                    showName:'database_bean,数据库bean 名称service_write_source,service_read_source',
                    name:"database_bean",
                    must_send:false,
                    must_save:false,
                    type:"input",
                    placeholder:"数据库bean 名称",
                    value:""
                  },
                  {
                          showName:'database_bean_disable,数据库bean 名称,是否禁用，1表示禁用。读和写只需要存在一个0',
                          name:"database_bean_disable",
                          must_send:false,
                          must_save:false,
                          type:"input",
                          placeholder:"数据库",
                          value:"1"
                  },

  				{
                        showName:'fields',
                        name:"fields",
                        must_send:false,
                        must_save:false,
                        type:"array",
                        placeholder:"",
                        value:[
                            {
                                "field_1":"connection_update",
                                "field_1_placeholder":"是否更改连接",
                                "field_2":"是否更改连接",
                                "field_2_placeholder":"",
                                "field_3":"S",
                                "field_3_placeholder":"",
                                "field_4":"",
                                "field_4_placeholder":"",
                                "field_5":"false",
                                "field_5_placeholder":"默认值"
                            },
                             {
                                "field_1":"table_update",
                                "field_1_placeholder":"是否更新表结构",
                                "field_2":"是否更新表结构",
                                "field_2_placeholder":"",
                                "field_3":"S",
                                "field_3_placeholder":"",
                                "field_4":"",
                                "field_4_placeholder":"",
                                "field_5":"false",
                                "field_5_placeholder":"默认值"
                            }
                        ]
                },

  				{
  					showName:'property',
  					name:"property",
  					must_send:false,
  					must_save:false,
  					type:"array",
  					placeholder:"",
  					value:[
  						
  							{
  								"field_1":"initialSize",
	  							"field_1_placeholder":"连接池数",
	  							"field_2":"连接数",
	  							"field_2_placeholder":"",
	  							"field_3":"I",
	  							"field_3_placeholder":"",
	  							"field_4":"",
	  							"field_4_placeholder":"",
	  							"field_5":"1",
	  							"field_5_placeholder":"默认值"
  							}
  					]
  				}


  				]
		}
function get_config(){
    return _config
}